services:
  open-webui:
    build:
      context: .
      dockerfile: prod.Dockerfile
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    env_file:
      - .env
    ports:
      - ${OPEN_WEBUI_PORT-5173}:8080
    environment:
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 1.0.0.1

volumes:
  open-webui: {}
