name: Docker Image CI for GHCR
on:
  push:
    branches:
      - main  # Adjust the branch as needed
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (optional but recommended)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}

      # Step 4: Build and push the Docker image
      - name: Build and push the Docker image
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          # Convert the repository name to lowercase
          IMAGE_TAG=ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]'):latest
          
          echo "Building Docker image with tag: $IMAGE_TAG"

          # Build the Docker image
          docker build . --tag "$IMAGE_TAG"

          # Push the Docker image to GHCR
          docker push "$IMAGE_TAG"